# We set up anonymous authentication as this is for demos.
auth:
  strategy: anonymous
deployment:
  pod_annotations:
    sidecar.istio.io/inject: "false"
  accessible_namespaces:
  - '**'
  image_version: v1.31
  ingress_enabled: false
login_token:
  signing_key: CHANGEME
